# Properties of Dot Product - Lab

## Introduction

In this lab, you'll be practicing some interesting properties of a Dot Product-type matrix multiplication. Understanding these properties will become useful as you move forward with machine learning. The lab will require you to calculate results to provide a proof for these properties.

## Objectives
You will be able to:
* Understand and analytically explain Distributive, Commutative and Associative properties of dot product

## Instructions

* For each property, create suitably sized matrices with random data and prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - matrix multiplication is distributive

### Prove that $A \cdot (B+C) = (A \cdot B + A \cdot C) $

In [1]:
import numpy as np


In [2]:
A = np.mat(np.random.randint(-100,100,[4,4]))
B = np.mat(np.random.randint(-100,100,[4,4]))
C = np.mat(np.random.randint(-100,100,[4,4]))


In [3]:
print(np.matmul(A,(B+C)))
print(' ')
print(np.matmul(A,B)+np.matmul(A,C))

[[ 10402  -6742   4891   4779]
 [  4917   3869    652 -13668]
 [ 13753  -2261   8940    620]
 [-17257  -4945  -4065   7391]]
 
[[ 10402  -6742   4891   4779]
 [  4917   3869    652 -13668]
 [ 13753  -2261   8940    620]
 [-17257  -4945  -4065   7391]]


## Associative Property - matrix multiplication is associative
### Prove that $A \cdot (B \cdot C) = (A \cdot B) \cdot C $

In [4]:
print(A.dot(B.dot(C)))
print(' ')
print((A.dot(B)).dot(C))

[[  -86324  -500466   798920   529570]
 [   38737   275097   527154  -919235]
 [ -350428   237698   447080  -912300]
 [ -779206   460752 -1197514    75710]]
 
[[  -86324  -500466   798920   529570]
 [   38737   275097   527154  -919235]
 [ -350428   237698   447080  -912300]
 [ -779206   460752 -1197514    75710]]


## Commutative Property - matrix multiplication is NOT commutative
### Prove that for matrices, $A \cdot B \neq B \cdot A $

In [7]:
print(A.dot(B))
print(' ')
print(B.dot(A))
print(' ')
print(np.matmul(A,B))
print(' ')
print(np.matmul(B,A))

[[  2258  -3650 -10745  11020]
 [  7306  -1758    878  -3891]
 [  8246  -1280   1785   -620]
 [ -2988  -5222   9027   2356]]
 
[[ -4562  12312   -995   9063]
 [-12567   4802  19935  12228]
 [  1259  -3482  -6392  -1883]
 [ -5192   2902  -5425  10793]]
 
[[  2258  -3650 -10745  11020]
 [  7306  -1758    878  -3891]
 [  8246  -1280   1785   -620]
 [ -2988  -5222   9027   2356]]
 
[[ -4562  12312   -995   9063]
 [-12567   4802  19935  12228]
 [  1259  -3482  -6392  -1883]
 [ -5192   2902  -5425  10793]]


## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors,  $x^T \cdot y = y^T \cdot x$
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [8]:
x = np.random.randint(-10,10, 5)
y = np.random.randint(-10,10, 5)

print(x)
print(y)

x.transpose().dot(y) == y.transpose().dot(x)


[ -3   4  -6 -10  -8]
[-6 -7  0 -4  1]


True

In [15]:


print((A.transpose()).dot(B))
print(" ")
print((B.transpose()).dot(A))


[[  -131 -12384    776  10584]
 [-10345   3699   6310  -2697]
 [ 11139   3504  -7884  -4004]
 [  3063  -3417  -1372   1993]]
 
[[  -131 -10345  11139   3063]
 [-12384   3699   3504  -3417]
 [   776   6310  -7884  -1372]
 [ 10584  -2697  -4004   1993]]


In [2]:
import numpy as np

## Simplification of the matrix product
### Prove that $ (A \cdot B)^T = B^T \cdot A^T $

In [3]:
A = np.mat(np.random.randint(-100,100,[4,4]))
B = np.mat(np.random.randint(-100,100,[4,4]))
C = np.mat(np.random.randint(-100,100,[4,4]))

(A.dot(B)).transpose() == B.transpose().dot(A.transpose())

matrix([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

## Summary 

You've seen enough matrix algebra by now to solve a problem of linear equations as you saw earlier. You'll now see how to do this next. 